[build]
builder = "nixpacks"
buildCommand = "yarn install && yarn prisma generate && yarn build"

[deploy]
startCommand = "yarn start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[nixpacks]
nixPkgs = ["nodejs_22"]
