[build]
builder = "nixpacks"
buildCommand = "bun install && bunx prisma generate && bun run build"

[deploy]
startCommand = "bun run start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[nixpacks]
nixPkgs = ["nodejs_22", "bun"]
