[build]
builder = "nixpacks"
installCommand = "bun install"
buildCommand = "bunx prisma generate && bun run build"
preDeployCommand="bunx prisma migrate deploy && bunx prisma generate"
[deploy]
startCommand = "bun run start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[nixpacks]
nixPkgs = ["nodejs_22", "bun"]
